Customised/Plugins/Nop.Plugin.Tax.Avalara/Controllers/AvalaraProductController.cs
using Microsoft.AspNetCore.Mvc;
using Nop.Plugin.Tax.Avalara.Services;
using Nop.Services.Localization;
using Nop.Services.Messages;
using Nop.Services.Security;
using Nop.Services.Tax;
using Nop.Web.Areas.Admin.Controllers;

namespace Nop.Plugin.Tax.Avalara.Controllers
{
    public class AvalaraProductController : BaseAdminController
    {
        #region Fields

        private readonly AvalaraTaxManager _avalaraTaxManager;
        private readonly ILocalizationService _localizationService;
        private readonly INotificationService _notificationService;
        private readonly IPermissionService _permissionService;
        private readonly ITaxPluginManager _taxPluginManager;

        #endregion

        #region Ctor

        public AvalaraProductController(AvalaraTaxManager avalaraTaxManager,
            ILocalizationService localizationService,
            INotificationService notificationService,
            IPermissionService permissionService,
            ITaxPluginManager taxPluginManager)
        {
            _avalaraTaxManager = avalaraTaxManager;
            _localizationService = localizationService;
            _notificationService = notificationService;
            _permissionService = permissionService;
            _taxPluginManager = taxPluginManager;
        }

        #endregion

        #region Methods

        [HttpPost]
        public IActionResult ExportProducts(string selectedIds)
        {
            //ensure that Avalara tax provider is active
            if (!_taxPluginManager.IsPluginActive(AvalaraTaxDefaults.SystemName))
                return RedirectToAction("List", "Product");

            if (!_permissionService.Authorize(StandardPermissionProvider.ManageTaxSettings))
                return AccessDeniedView();

            //export items
            var exportedItems = _avalaraTaxManager.ExportProducts(selectedIds);
            if (exportedItems.HasValue)
            {
                if (exportedItems > 0)
                    _notificationService.SuccessNotification(string.Format(_localizationService.GetResource("Plugins.Tax.Avalara.Items.Export.Success"), exportedItems));
                else
                    _notificationService.SuccessNotification(_localizationService.GetResource("Plugins.Tax.Avalara.Items.Export.AlreadyExported"));
            }
            else
                _notificationService.ErrorNotification(_localizationService.GetResource("Plugins.Tax.Avalara.Items.Export.Error"));

            return RedirectToAction("List", "Product");
        }

        #endregion
    }
}

Customised/Plugins/Nop.Plugin.Tax.Avalara/Views/Product/ExportItems.cshtml
<script>
    $(document).ready(function () {
        $('#delete-selected').before(`@await Html.PartialAsync("~/Plugins/Tax.Avalara/Views/Product/_ExportItemsButton.cshtml")`);
        $('#export-excel-selected-form').after(`@Html.Raw((await Html.PartialAsync("~/Plugins/Tax.Avalara/Views/Product/_ExportItemsForm.cshtml")).ToHtmlString().Replace("</script>", "<\\/script>"))`);
    });
</script>

Customised/Plugins/Nop.Plugin.Tax.Avalara/Views/Product/_ExportItemsButton.cshtml
<button type="button" id="export-avalara-selected" class="btn btn-warning" style="margin-right: 4px">
    <i class="fa fa-exchange"></i>
    @T("Plugins.Tax.Avalara.Items.Export")
</button>

Customised/Plugins/Nop.Plugin.Tax.Avalara/Views/Product/_ExportItemsForm.cshtml
<form asp-controller="AvalaraProduct" asp-action="ExportProducts" method="post" id="export-avalara-selected-form">
    <script>
        $(document).ready(function () {
            $('#export-avalara-selected').click(function (e) {
                e.preventDefault();
                var ids = selectedIds.join(",");
                if (!ids) {
                    $('#export-avalara-selected-alert-info').text("@T("Admin.Products.NoProducts")");
                    $("#export-avalara-selected-alert").click();
                }
                else {
                    $('#export-avalara-selected-form #selectedIds').val(ids);
                    $('#export-avalara-selected-form').submit();
                    updateTable('#products-grid');
                }
                return false;
            });
        });
    </script>
    <nop-alert asp-alert-id="export-avalara-selected-alert" />
    <input type="hidden" id="selectedIds" name="selectedIds" value="" />
</form>