Customised/Plugins/Nop.Plugin.Pickup.PickupInStore/Controllers/PickupInStoreController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Nop.Core.Domain.Common;
using Nop.Core.Domain.Directory;
using Nop.Plugin.Pickup.PickupInStore.Domain;
using Nop.Plugin.Pickup.PickupInStore.Factories;
using Nop.Plugin.Pickup.PickupInStore.Models;
using Nop.Plugin.Pickup.PickupInStore.Services;
using Nop.Services.Common;
using Nop.Services.Directory;
using Nop.Services.Localization;
using Nop.Services.Security;
using Nop.Services.Stores;
using Nop.Web.Framework;
using Nop.Web.Framework.Controllers;
using Nop.Web.Framework.Mvc;
using Nop.Web.Framework.Mvc.Filters;

namespace Nop.Plugin.Pickup.PickupInStore.Controllers
{
    [Area(AreaNames.Admin)]
    [AuthorizeAdmin]
    [AutoValidateAntiforgeryToken]
    public class PickupInStoreController : BasePluginController
    {
        #region Fields

        private readonly IAddressService _addressService;
        private readonly ICountryService _countryService;
        private readonly ILocalizationService _localizationService;
        private readonly IPermissionService _permissionService;
        private readonly IStateProvinceService _stateProvinceService;
        private readonly IStorePickupPointModelFactory _storePickupPointModelFactory;
        private readonly IStorePickupPointService _storePickupPointService;
        private readonly IStoreService _storeService;
        private readonly AddressSettings _addressSettings;

        #endregion

        #region Ctor

        public PickupInStoreController(IAddressService addressService,
            ICountryService countryService,
            ILocalizationService localizationService,
            IPermissionService permissionService,
            IStateProvinceService stateProvinceService,
            IStorePickupPointModelFactory storePickupPointModelFactory,
            IStorePickupPointService storePickupPointService,
            IStoreService storeService,
            AddressSettings customerSettings)
        {
            _addressService = addressService;
            _countryService = countryService;
            _localizationService = localizationService;
            _permissionService = permissionService;
            _stateProvinceService = stateProvinceService;
            _storePickupPointModelFactory = storePickupPointModelFactory;
            _storePickupPointService = storePickupPointService;
            _storeService = storeService;
            _addressSettings = customerSettings;
        }

        #endregion

        #region Methods

        public IActionResult Configure()
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageShippingSettings))
                return AccessDeniedView();

            //prepare model
            var model = _storePickupPointModelFactory.PrepareStorePickupPointSearchModel(new StorePickupPointSearchModel());

            return View("~/Plugins/Pickup.PickupInStore/Views/Configure.cshtml", model);
        }

        [HttpPost]
        public IActionResult List(StorePickupPointSearchModel searchModel)
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageShippingSettings))
                return AccessDeniedDataTablesJson();

            //prepare model
            var model = _storePickupPointModelFactory.PrepareStorePickupPointListModel(searchModel);

            return Json(model);
        }

        public IActionResult Create()
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageShippingSettings))
                return AccessDeniedView();

            var model = new StorePickupPointModel
            {
                Address =
                {
                    CountryEnabled = _addressSettings.CountryEnabled,
                    StateProvinceEnabled = _addressSettings.StateProvinceEnabled,
                    ZipPostalCodeEnabled = _addressSettings.ZipPostalCodeEnabled,
                    CityEnabled = _addressSettings.CityEnabled,
                    CountyEnabled = _addressSettings.CountyEnabled
                }
            };

            model.Address.AvailableCountries.Add(new SelectListItem { Text = _localizationService.GetResource("Admin.Address.SelectCountry"), Value = "0" });
            foreach (var country in _countryService.GetAllCountries(showHidden: true))
                model.Address.AvailableCountries.Add(new SelectListItem { Text = country.Name, Value = country.Id.ToString() });

            var states = !model.Address.CountryId.HasValue ? new List<StateProvince>()
                : _stateProvinceService.GetStateProvincesByCountryId(model.Address.CountryId.Value, showHidden: true);
            if (states.Any())
            {
                model.Address.AvailableStates.Add(new SelectListItem { Text = _localizationService.GetResource("Admin.Address.SelectState"), Value = "0" });
                foreach (var state in states)
                    model.Address.AvailableStates.Add(new SelectListItem { Text = state.Name, Value = state.Id.ToString() });
            }
            else
                model.Address.AvailableStates.Add(new SelectListItem { Text = _localizationService.GetResource("Admin.Address.Other"), Value = "0" });

            model.AvailableStores.Add(new SelectListItem { Text = _localizationService.GetResource("Admin.Configuration.Settings.StoreScope.AllStores"), Value = "0" });
            foreach (var store in _storeService.GetAllStores())
                model.AvailableStores.Add(new SelectListItem { Text = store.Name, Value = store.Id.ToString() });

            return View("~/Plugins/Pickup.PickupInStore/Views/Create.cshtml", model);
        }

        [HttpPost]
        public IActionResult Create(StorePickupPointModel model)
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageShippingSettings))
                return AccessDeniedView();

            var address = new Address
            {
                Address1 = model.Address.Address1,
                City = model.Address.City,
                County = model.Address.County,
                CountryId = model.Address.CountryId,
                StateProvinceId = model.Address.StateProvinceId,
                ZipPostalCode = model.Address.ZipPostalCode,
                CreatedOnUtc = DateTime.UtcNow
            };
            _addressService.InsertAddress(address);

            var pickupPoint = new StorePickupPoint
            {
                Name = model.Name,
                Description = model.Description,
                AddressId = address.Id,
                OpeningHours = model.OpeningHours,
                PickupFee = model.PickupFee,
                DisplayOrder = model.DisplayOrder,
                StoreId = model.StoreId,
                Latitude = model.Latitude,
                Longitude = model.Longitude,
                TransitDays = model.TransitDays
            };
            _storePickupPointService.InsertStorePickupPoint(pickupPoint);

            ViewBag.RefreshPage = true;

            return View("~/Plugins/Pickup.PickupInStore/Views/Create.cshtml", model);
        }

        public IActionResult Edit(int id)
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageShippingSettings))
                return AccessDeniedView();

            var pickupPoint = _storePickupPointService.GetStorePickupPointById(id);
            if (pickupPoint == null)
                return RedirectToAction("Configure");

            var model = new StorePickupPointModel
            {
                Id = pickupPoint.Id,
                Name = pickupPoint.Name,
                Description = pickupPoint.Description,
                OpeningHours = pickupPoint.OpeningHours,
                PickupFee = pickupPoint.PickupFee,
                DisplayOrder = pickupPoint.DisplayOrder,
                StoreId = pickupPoint.StoreId,
                Latitude = pickupPoint.Latitude,
                Longitude = pickupPoint.Longitude,
                TransitDays = pickupPoint.TransitDays
            };

            var address = _addressService.GetAddressById(pickupPoint.AddressId);
            if (address != null)
            {
                model.Address = new AddressModel
                {
                    Address1 = address.Address1,
                    City = address.City,
                    County = address.County,
                    CountryId = address.CountryId,
                    StateProvinceId = address.StateProvinceId,
                    ZipPostalCode = address.ZipPostalCode,
                    CountryEnabled = _addressSettings.CountryEnabled,
                    StateProvinceEnabled = _addressSettings.StateProvinceEnabled,
                    ZipPostalCodeEnabled = _addressSettings.ZipPostalCodeEnabled,
                    CityEnabled = _addressSettings.CityEnabled,
                    CountyEnabled = _addressSettings.CountyEnabled
                };
            }

            model.Address.AvailableCountries.Add(new SelectListItem { Text = _localizationService.GetResource("Admin.Address.SelectCountry"), Value = "0" });
            foreach (var country in _countryService.GetAllCountries(showHidden: true))
                model.Address.AvailableCountries.Add(new SelectListItem { Text = country.Name, Value = country.Id.ToString(), Selected = (address != null && country.Id == address.CountryId) });

            var states = !model.Address.CountryId.HasValue ? new List<StateProvince>()
                : _stateProvinceService.GetStateProvincesByCountryId(model.Address.CountryId.Value, showHidden: true);
            if (states.Any())
            {
                model.Address.AvailableStates.Add(new SelectListItem { Text = _localizationService.GetResource("Admin.Address.SelectState"), Value = "0" });
                foreach (var state in states)

Customised/Plugins/Nop.Plugin.Pickup.PickupInStore/Views/Configure.cshtml
@inject Nop.Core.Domain.Common.AdminAreaSettings adminAreaSettings
@using Nop.Plugin.Pickup.PickupInStore.Models
@using Nop.Web.Framework.Models.DataTables
@model StorePickupPointSearchModel
@{
    Layout = "_ConfigurePlugin";
}

<form asp-controller="PickupInStore" asp-action="Configure" method="post" id="pickup-instore-form">
    <div class="panel-group">
        <div class="panel panel-default">
            <div class="panel-body">
                @await Html.PartialAsync("Table", new DataTablesModel
           {
               Name = "pickup-points-grid",
               UrlRead = new DataUrl("List", "PickupInStore", null),
               UrlDelete = new DataUrl("Delete", "PickupInStore", null),
               Length = Model.PageSize,
               LengthMenu = Model.AvailablePageSizes,
               ColumnCollection = new List<ColumnProperty>
                {
                    new ColumnProperty(nameof(StorePickupPointModel.Name))
                    {
                        Title = T("Plugins.Pickup.PickupInStore.Fields.Name").Text,
                        Width = "200"
                    },
                    new ColumnProperty(nameof(StorePickupPointModel.OpeningHours))
                    {
                        Title = T("Plugins.Pickup.PickupInStore.Fields.OpeningHours").Text,
                        Width = "200"
                    },
                    new ColumnProperty(nameof(StorePickupPointModel.PickupFee))
                    {
                        Title = T("Plugins.Pickup.PickupInStore.Fields.PickupFee").Text,
                        Width = "100"
                    },
                    new ColumnProperty(nameof(StorePickupPointModel.DisplayOrder))
                    {
                        Title = T("Plugins.Pickup.PickupInStore.Fields.DisplayOrder").Text,
                        Width = "100"
                    },
                    new ColumnProperty(nameof(StorePickupPointModel.StoreName))
                    {
                        Title = T("Plugins.Pickup.PickupInStore.Fields.Store").Text,
                        Width = "100"
                    },
                    new ColumnProperty(nameof(StorePickupPointModel.Id))
                    {
                        Title = T("Admin.Common.Edit").Text,
                        ClassName = NopColumnClassDefaults.Button,
                        Width = "100",
                        Render = new RenderCustom("renderColumnEdit")
                    },
                    new ColumnProperty(nameof(StorePickupPointModel.Id))
                    {
                        Title = T("Admin.Common.Delete").Text,
                        ClassName = NopColumnClassDefaults.Button,
                        Render = new RenderButtonRemove(T("Admin.Common.Delete").Text),
                        Width = "100"
                    }
                }
           })
            </div>

            <script>
                function renderColumnEdit(data, type, row, meta) {
                    return '<button onclick=\"javascript:OpenWindow(\'@Url.Content("~/Admin/PickupInStore/Edit/")' + data + '?btnId=btnRefresh&formId=pickup-instore-form\', 800, 800, true); return false;\" class="btn btn-default"><i class="fa fa-pencil"></i>@T("Admin.Common.Edit")</button>';
                }
            </script>

            <div class="panel-footer">
                <input type="submit" id="btnAddNewOption" class="btn btn-primary" value="@T("Plugins.Pickup.PickupInStore.AddNew")" onclick="javascript:OpenWindow('@(Url.Action("Create", "PickupInStore",  new { btnId = "btnRefresh", formId = "pickup-instore-form" }))', 800, 800, true); return false;"/>
                <input type="submit" id="btnRefresh" class="btn btn-default" style="display: none" />
            </div>
            <script>
                $(document).ready(function () {
                    $('#btnRefresh').click(function () {
                        //refresh grid
                        updateTable('#pickup-points-grid');

                        //return false to don't reload a page
                        return false;
                    });
                });
            </script>
        </div>
    </div>
</form>

Customised/Plugins/Nop.Plugin.Pickup.PickupInStore/Views/Create.cshtml
@model Nop.Plugin.Pickup.PickupInStore.Models.StorePickupPointModel
@{
    Layout = "~/Areas/Admin/Views/Shared/_AdminPopupLayout.cshtml";
}

<form asp-controller="PickupInStore" asp-action="Create"
      asp-route-btnId="@Context.Request.Query["btnId"]"
      asp-route-formId="@Context.Request.Query["formId"]">
    <div class="content-header clearfix">
        <h1 class="pull-left">
            @T("Admin.Common.AddNew")
        </h1>
        <div class="pull-right">
            <button type="submit" name="save" class="btn bg-blue">
                <i class="fa fa-floppy-o"></i>
                @T("Admin.Common.Save")
            </button>
        </div>
    </div>

    <div class="content">
        <div class="form-horizontal">
            @await Html.PartialAsync("~/Plugins/Pickup.PickupInStore/Views/_CreateOrUpdate.cshtml", Model)
        </div>
    </div>
</form>

Customised/Plugins/Nop.Plugin.Pickup.PickupInStore/Views/Edit.cshtml
@model Nop.Plugin.Pickup.PickupInStore.Models.StorePickupPointModel
@{
    Layout = "~/Areas/Admin/Views/Shared/_AdminPopupLayout.cshtml";
}

<form asp-controller="PickupInStore" asp-action="Edit"
      asp-route-btnId="@Context.Request.Query["btnId"]"
      asp-route-formId="@Context.Request.Query["formId"]">
    <div class="content-header clearfix">
        <h1 class="pull-left">
            @T("Admin.Common.Edit")
        </h1>
        <div class="pull-right">
            <button type="submit" name="save" class="btn bg-blue">
                <i class="fa fa-floppy-o"></i>
                @T("Admin.Common.Save")
            </button>
        </div>
    </div>

    <div class="content">
        <div class="form-horizontal">
            @await Html.PartialAsync("~/Plugins/Pickup.PickupInStore/Views/_CreateOrUpdate.cshtml", Model)
        </div>
    </div>
</form>

Customised/Plugins/Nop.Plugin.Pickup.PickupInStore/Views/_CreateOrUpdate.cshtml
@model Nop.Plugin.Pickup.PickupInStore.Models.StorePickupPointModel

<div asp-validation-summary="All"></div>
<input asp-for="Id" type="hidden" />

@if (ViewBag.RefreshPage == true)
{
    <script>
        try {window.opener.document.forms['@(Context.Request.Query["formId"])'].@(Context.Request.Query["btnId"]).click();}
        catch (e){}
        window.close();
    </script>
}

<div class="panel-group">
    <div class="panel panel-default panel-popup">

        <script>
            $(document).ready(function() {
                $("#@Html.IdFor(model => model.Address.CountryId)").change(function(){
                    var selectedItem = $(this).val();
                    var ddlStates = $("#@Html.IdFor(model => model.Address.StateProvinceId)");
                    $.ajax({
                        cache: false,
                        type: "GET",
                        url: "@(Url.Action("GetStatesByCountryId", "Country"))",
                        data: {
                            "countryId": selectedItem
                        },
                        success: function (data, textStatus, jqXHR) {
                            ddlStates.html('');
                            $.each(data, function(id, option) {
                                ddlStates.append($('<option></option>').val(option.id).html(option.name));
                            });
                        },
                        error: function (jqXHR, textStatus, errorThrown) {
                            $("#getStatesByCountryIdAlert").click();
                        }
                    });
                });
            });
        </script>

        <div class="panel-body">
            <div class="form-group">
                <div class="col-sm-3">
                    <nop-label asp-for="Name" />
                </div>
                <div class="col-sm-9">
                    <nop-editor asp-for="Name" />
                    <span asp-validation-for="Name"></span>
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-3">
                    <nop-label asp-for="Description" />
                </div>
                <div class="col-sm-9">
                    <nop-textarea asp-for="Description" />
                    <span asp-validation-for="Description"></span>
                </div>
            </div>
            @if (Model.Address.CountryEnabled)
            {
                <div class="form-group">
                    <div class="col-sm-3">
                        <nop-label asp-for="Address.CountryId" />
                    </div>
                    <div class="col-sm-9">
                        <nop-select asp-for="Address.CountryId" asp-items="Model.Address.AvailableCountries" />
                        <span asp-validation-for="Address.CountryId"></span>
                    </div>
                </div>
            }
            @if (Model.Address.StateProvinceEnabled)
            {
                <div class="form-group">
                    <div class="col-sm-3">
                        <nop-label asp-for="Address.StateProvinceId" />
                    </div>
                    <div class="col-sm-9">
                        <nop-select asp-for="Address.StateProvinceId" asp-items="Model.Address.AvailableStates" />
                        <span asp-validation-for="Address.StateProvinceId"></span>
                    </div>
                </div>
            }
            @if (Model.Address.CountyEnabled)
            {
                <div class="form-group">
                    <div class="col-sm-3">
                        <nop-label asp-for="Address.County" />
                    </div>
                    <div class="col-sm-9">
                        <nop-editor asp-for="Address.County" />
                        <span asp-validation-for="Address.County"></span>
                    </div>
                </div>
            }
            @if (Model.Address.CityEnabled)
            {
                <div class="form-group">
                    <div class="col-sm-3">
                        <nop-label asp-for="Address.City" />
                    </div>
                    <div class="col-sm-9">
                        <nop-editor asp-for="Address.City" />
                        <span asp-validation-for="Address.City"></span>
                    </div>
                </div>
            }
            <div class="form-group">
                <div class="col-sm-3">
                    <nop-label asp-for="Address.Address1" />
                </div>
                <div class="col-sm-9">
                    <nop-editor asp-for="Address.Address1" />
                    <span asp-validation-for="Address.Address1"></span>
                </div>
            </div>
            @if (Model.Address.ZipPostalCodeEnabled)
            {
                <div class="form-group">
                    <div class="col-sm-3">
                        <nop-label asp-for="Address.ZipPostalCode" />
                    </div>
                    <div class="col-sm-9">
                        <nop-editor asp-for="Address.ZipPostalCode" />
                        <span asp-validation-for="Address.ZipPostalCode"></span>
                    </div>
                </div>
            }
            <div class="form-group">
                <div class="col-sm-3">
                    <nop-label asp-for="OpeningHours" />
                </div>
                <div class="col-sm-9">
                    <nop-editor asp-for="OpeningHours" />
                    <span asp-validation-for="OpeningHours"></span>
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-3">
                    <nop-label asp-for="PickupFee" />
                </div>
                <div class="col-sm-9">
                    <nop-editor asp-for="PickupFee" />
                    <span asp-validation-for="PickupFee"></span>
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-3">
                    <nop-label asp-for="DisplayOrder" />
                </div>
                <div class="col-sm-9">
                    <nop-editor asp-for="DisplayOrder" />
                    <span asp-validation-for="DisplayOrder"></span>
                </div>
            </div>
            <div class="form-group" @(Model.AvailableStores.SelectionIsNotPossible() ? Html.Raw("style=\"display:none\"") : null)>
                <div class="col-sm-3">
                    <nop-label asp-for="StoreId" />
                </div>
                <div class="col-sm-9">
                    <nop-select asp-for="StoreId" asp-items="Model.AvailableStores" />
                    <span asp-validation-for="StoreId"></span>
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-3">
                    <nop-label asp-for="Latitude" />
                </div>
                <div class="col-sm-9">
                    <nop-editor asp-for="Latitude" asp-render-form-control-class="true" />
                    <span asp-validation-for="Latitude"></span>
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-3">
                    <nop-label asp-for="Longitude" />
                </div>
                <div class="col-sm-9">
                    <nop-editor asp-for="Longitude" asp-render-form-control-class="true" />
                    <span asp-validation-for="Longitude"></span>
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-3">
                    <nop-label asp-for="TransitDays" />
                </div>
                <div class="col-sm-9">
                    <nop-editor asp-for="TransitDays" />
                    <span asp-validation-for="TransitDays"></span>
                </div>
            </div>
        </div>
    </div>
</div>
<nop-alert asp-alert-id="getStatesByCountryIdAlert" asp-alert-message="@T("Admin.Common.Alert.States.Failed")" />